name: Testar
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - '**'
jobs:
  testar:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test